stages:
  - setup
  - build

services:
  - docker:dind

# rebuild docker containers if they changed.
setup:docker:
  image: docker
  stage: setup
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - >
      if ! git diff --exit-code Dockerfile.bionic; then
        docker build . -f Dockerfile.bionic -t "$CI_REGISTRY_IMAGE:bionic"
        docker push "$CI_REGISTRY_IMAGE:bionic"
      else
        echo "Skipping rebuilding bionic, Dockerfile hasn't changed."
      fi
    - >
      if ! git diff --exit-code Dockerfile.alpine; then
        docker build . -f Dockerfile.alpine -t "$CI_REGISTRY_IMAGE:alpine"
        docker push "$CI_REGISTRY_IMAGE:alpine"
      else
        echo "Skipping rebuilding bionic, Dockerfile hasn't changed."
      fi
  only:
    - master

# build stuff on ubuntu.
build:bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - apt update && apt install -y gcc clang make cmake
    - mkdir build && cd build && cmake .. && make

# build stuff on alpine.
build:alpine:
  image: alpine:latest
  stage: build
  script:
    - apk add build-base cmake make
    - mkdir build && cd build && cmake .. && make
