# makes git submodules work
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - build
  - release

# rebuild alpine docker container.
docker:alpine:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f Dockerfile.alpine -t "$CI_REGISTRY_IMAGE:alpine"
    - docker push "$CI_REGISTRY_IMAGE:alpine"
  only:
    - docker

# rebuild bionic docker container
docker:bionic:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f Dockerfile.bionic -t "$CI_REGISTRY_IMAGE:bionic"
    - docker push "$CI_REGISTRY_IMAGE:bionic"
  only:
    - docker

# build stuff on ubuntu.
build:bionic:debug:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: build
  script:
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - ninja
    - ./tests/passgen-test

build:bionic:release:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: build
  script:
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - ninja
    - ./tests/passgen-test

# build stuff on alpine.
build:alpine:release:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: build
  script:
    - mkdir -p build-alpine-release && cd build-alpine-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=y ..
    - ninja
    - ./tests/passgen-test
  artifacts:
    paths:
      - build-alpine-release
    expire_in: 1 week

# alpine uses musl libc by default which does not have a backtrace() function
# built-in. therefore, the debug build needs USE_LIBEXECINFO to build.
build:alpine:debug:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: build
  script:
    - mkdir build-alpine-debug && cd build-alpine-debug
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DUSE_LIBEXECINFO=y ..
    - ninja
    - ./tests/passgen-test
  artifacts:
    paths:
      - build-alpine-debug
    expire_in: 1 week

release:alpine:
    image: registry.gitlab.com/xfbs/passgen:bionic
    stage: release
    dependencies:
      - build:alpine:debug
    script:
      - mkdir release
      - cp build-alpine-debug/libpassgen/libpassgen.a build-alpine-debug/tests/passgen-test release
      - tar c -f release.tar.xz -J release
    artifacts:
      paths:
        - release.tar.xz
