# makes git submodules work
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - test
  - build
  - deploy

# rebuild alpine docker container.
docker:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f scripts/alpine.Dockerfile -t "$CI_REGISTRY_IMAGE:alpine"
    - docker build . -f scripts/bionic.Dockerfile -t "$CI_REGISTRY_IMAGE:bionic"
    - docker build . -f scripts/deploy.Dockerfile -t "$CI_REGISTRY_IMAGE:deploy"
    - docker push "$CI_REGISTRY_IMAGE:alpine"
    - docker push "$CI_REGISTRY_IMAGE:bionic"
    - docker push "$CI_REGISTRY_IMAGE:deploy"
  only:
    - docker

sanitize:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: test
  script:
    - CC=clang-10 scripts/run_sanitizer.sh Address
    - CC=clang-10 scripts/run_sanitizer.sh Memory
    - CC=clang-10 scripts/run_sanitizer.sh Undefined
    - CC=clang-10 scripts/run_sanitizer.sh Leak

test:bionic:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: test
  script:
    - CC=clang-10 ./scripts/gen_coverage.sh passgen-test build-clang
    - CC=gcc ./scripts/gen_coverage.sh passgen-test build-gcc
  artifacts:
    paths:
      - build-clang/ccov/passgen-test
      - build-gcc/ccov/passgen-test
    expire_in: 1 week

# build stuff on ubuntu.
build:bionic:release:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: build
  script:
    - mkdir build-bionic-release && cd build-bionic-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_GIT_INFO=NO ..
    - ninja
    - ./tests/passgen-test
  artifacts:
    paths:
      - build-bionic-release
    expire_in: 1 week

# build stuff on alpine.
build:alpine:release:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: build
  script:
    - mkdir -p build-alpine-release && cd build-alpine-release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_GIT_INFO=NO -DBUILD_STATIC=y ..
    - ninja
    - ./tests/passgen-test
  artifacts:
    paths:
      - build-alpine-release
    expire_in: 1 week

pages:
  image: registry.gitlab.com/xfbs/passgen:deploy
  stage: deploy
  dependencies:
    - test:bionic
  script:
    - mkdir -p public/coverage
    - mv build-clang/ccov/passgen-test public/coverage/llvm-cov
    - mv build-gcc/ccov/passgen-test public/coverage/lcov
    - doxygen Doxyfile
    - mv docs/html public/doxygen
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
