image: debian:11

# makes git submodules work
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - test
  - build
  - deploy

# rebuild alpine docker container.
docker:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f scripts/alpine.Dockerfile -t "$CI_REGISTRY_IMAGE:alpine"
    - docker build . -f scripts/bionic.Dockerfile -t "$CI_REGISTRY_IMAGE:bionic"
    - docker build . -f scripts/deploy.Dockerfile -t "$CI_REGISTRY_IMAGE:deploy"
    - docker build . -f scripts/osxcross.Dockerfile -t "$CI_REGISTRY_IMAGE:osxcross"
    - docker push "$CI_REGISTRY_IMAGE:alpine"
    - docker push "$CI_REGISTRY_IMAGE:bionic"
    - docker push "$CI_REGISTRY_IMAGE:deploy"
    - docker push "$CI_REGISTRY_IMAGE:osxcross"
  only:
    - docker

docker:riscv64:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f scripts/riscv64.dockerfile -t "$CI_REGISTRY_IMAGE/riscv64"
    - docker push "$CI_REGISTRY_IMAGE/riscv64"
  only:
    refs:
      - master
    changes:
      - scripts/riscv64.dockerfile

sanitize:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: test
  script:
    - CC=clang-10 scripts/run_sanitizer.sh Address
    - CC=clang-10 scripts/run_sanitizer.sh Memory
    - CC=clang-10 scripts/run_sanitizer.sh Undefined
    - CC=clang-10 scripts/run_sanitizer.sh Leak

test:bionic:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: test
  script:
    - CC=clang-10 ./scripts/gen_coverage.sh passgen-test build-clang
    - CC=gcc ./scripts/gen_coverage.sh passgen-test build-gcc
  artifacts:
    paths:
      - build-clang/ccov/passgen-test
      - build-gcc/ccov/passgen-test
    expire_in: 1 week

test:alpine:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: test
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DUSE_BACKTRACE=NO -GNinja
    - cmake --build build
    - ./build/src/tests/passgen-test -v
    - valgrind ./build/src/tests/passgen-test -v

test:riscv64:
  image: registry.gitlab.com/xfbs/passgen/riscv64
  stage: test
  script:
    - cmake -S . -B build-riscv64 -GNinja -DCMAKE_TOOLCHAIN_FILE=scripts/riscv64-gcc.cmake -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build-riscv64
    - qemu-riscv64-static -L /usr/riscv64-linux-gnu/ ./build-riscv64/src/tests/passgen-test

build:riscv64:
  image: registry.gitlab.com/xfbs/passgen/riscv64
  stage: build
  script:
    - cmake -S . -B build-riscv64 -GNinja -DCMAKE_TOOLCHAIN_FILE=scripts/riscv64-gcc.cmake -DCMAKE_BUILD_TYPE=Release
    - cd build-riscv64
    - ninja
    - qemu-riscv64-static -L /usr/riscv64-linux-gnu/ ./src/tests/passgen-test
    - cpack -G TXZ
    - cpack -G DEB
  artifacts:
    paths:
      - build-riscv64
    expire_in: 1 week

# build stuff on ubuntu.
build:bionic:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: build
  script:
    - mkdir build-bionic-release && cd build-bionic-release
    - cmake -GNinja -DCMAKE_UNITY_BUILD=YES -DCMAKE_BUILD_TYPE=Release ..
    - ninja
    - ./src/tests/passgen-test
    - cpack -G TXZ
    - cpack -G DEB
  artifacts:
    paths:
      - build-bionic-release
    expire_in: 1 week

# build stuff on alpine.
build:alpine:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: build
  script:
    - mkdir -p build-alpine-release && cd build-alpine-release
    - cmake -GNinja -DCMAKE_UNITY_BUILD=YES -DCMAKE_BUILD_TYPE=Release -DPASSGEN_STATIC=y ..
    - ninja
    - ./src/tests/passgen-test
    - cpack -G TXZ
  artifacts:
    paths:
      - build-alpine-release
    expire_in: 1 week

build:osxcross:
  image: registry.gitlab.com/xfbs/passgen:osxcross
  stage: build
  variables:
    AR: /opt/osxcross/bin/x86_64-apple-darwin18-ar
    CC: /opt/osxcross/bin/x86_64h-apple-darwin18-clang
    RANLIB: /opt/osxcross/bin/x86_64h-apple-darwin18-ranlib
    CMAKE: /opt/cmake/bin/cmake
    CPACK: /opt/cmake/bin/cpack
  script:
    - $CMAKE -S . -B build-osx-release -DLIBPASSGEN_SHARED=NO -DCMAKE_BUILD_TYPE=Release -DBUILD_BENCH=NO -DCMAKE_AR=$AR -DCMAKE_RANLIB=$RANLIB
    - $CMAKE --build build-osx-release
    - cd build-osx-release && cpack -G TXZ
  artifacts:
    paths:
      - build-osx-release
    expire_in: 1 week

pages:
  image: registry.gitlab.com/xfbs/passgen:deploy
  stage: deploy
  dependencies:
    - test:bionic
    - build:alpine
    - build:bionic
    - build:osxcross
    - build:riscv64
  script:
    - mkdir -p public/coverage
    - mv build-clang/ccov/passgen-test public/coverage/llvm-cov
    - mv build-gcc/ccov/passgen-test public/coverage/lcov
    - doxygen Doxyfile
    - mv docs/html public/doxygen
    - mkdir public/badges
    - python3 scripts/docs_coverage.py docs/xml/ --badge public/badges/docs.svg --noerror
    - mkdir public/snapshot
    - cp build-alpine-release/passgen-*-Linux.tar.xz public/snapshot/passgen-master-musl-amd64.tar.xz
    - cp build-bionic-release/passgen-*-Linux.tar.xz public/snapshot/passgen-master-amd64.tar.xz
    - cp build-bionic-release/passgen_*_amd64.deb public/snapshot/passgen-master-amd64.deb
    - cp build-riscv64/passgen-*-Linux.tar.xz public/snapshot/passgen-master-riscv64.tar.xz
    - cp build-riscv64/passgen_*_riscv64.deb public/snapshot/passgen-master-riscv64.deb
    - cp build-osx-release/passgen-*-Linux.tar.xz public/snapshot/passgen-master-osx-amd64.tar.xz
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
