# makes git submodules work
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - build

# rebuild alpine docker container.
docker:alpine:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f Dockerfile.alpine -t "$CI_REGISTRY_IMAGE:alpine"
    - docker push "$CI_REGISTRY_IMAGE:alpine"
  only:
    - docker

# rebuild bionic docker container
docker:bionic:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -f Dockerfile.bionic -t "$CI_REGISTRY_IMAGE:bionic"
    - docker push "$CI_REGISTRY_IMAGE:bionic"
  only:
    - docker

# build stuff on ubuntu.
build:bionic:
  image: registry.gitlab.com/xfbs/passgen:bionic
  stage: build
  script:
    - mkdir build && cd build && cmake ..
    - make
    - ./tests/passgen-test

# build stuff on alpine.
build:alpine:
  image: registry.gitlab.com/xfbs/passgen:alpine
  stage: build
  script:
    - mkdir build && cd build && cmake .. -DUSE_LIBEXECINFO=y
    - make
    - ./tests/passgen-test
