#language: c
dist: xenial
#compiler:
#  - clang
#  - gcc
addons:
  apt:
    packages:
      - libsodium-dev
script: make test

sudo: true

os: linux
#dist: trusty

language: python

python: 3.6

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

install:
  - wget "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip"
  - wget "https://github.com/JuliaStrings/utf8proc/archive/v2.4.0.tar.gz" -o utf8proc.tar.gz
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - tar xvf utf8proc.tar.gz
  - cd utf8proc-* && make && sudo make install && cd ..
  - pip install meson
