#language: c
dist: xenial
#compiler:
#  - clang
#  - gcc
addons:
  apt:
    packages:
      - libutf8proc-dev
      - libutf8proc1
      - meson
      - libsodium-dev
      - libsodium18
script: make test

sudo: false

os: linux
#dist: trusty

language: python

python: 3.6

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

install:
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson
