language: c
dist: xenial
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libutf8proc-dev
      - libutf8proc1
      - meson
      - libsodium-dev
      - libsodium18
script: make test
