FROM ubuntu:bionic

RUN apt update && apt install -y build-essential sudo

RUN adduser --disabled-password --groups sudo --system --shell /bin/bash user
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user

RUN useradd -m docker && adduser docker sudo
