FROM ubuntu:bionic

# install essential stuff
RUN apt update && apt install -y sudo gcc ninja-build cmake git libjansson-dev

# create nonprivileged user to build stuff under with access to sudo
RUN adduser --disabled-password --ingroup sudo --shell /bin/bash --gecos '' user
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user
