site_name: Passgen
site_url: https://passgen.it

copyright: 'Copyright &copy; 2023 Patrick M. Elsen'

repo_name: 'xfbs/passgen'
repo_url: 'https://gitlab.com/xfbs/passgen'

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - kroki:
      DownloadImages: true
      DownloadDir: images

nav:
  - Home: index.md
  - Usage:
    - Usage: usage.md
    - Presets: presets.md
    - Syntax: syntax.md
    - Entropy: entropy.md
    - Randomness: randomness.md
  - Releases:
    - Nightly: nightly.md
    - WASI: wasi.md
    - Installation: install.md
  - Development:
    - Resources: development/index.md
    - Building: development/building.md
    - Tooling:
      - Overview: development/tooling.md
      - Testing: development/tooling/testing.md
      - Benchmarks: development/tooling/benchmarks.md
      - Sanitizers: development/tooling/sanitizers.md
      - Formatting: development/tooling/formatting.md
      - Includes: development/tooling/includes.md
      - Symbols: development/tooling/symbols.md
      - Coverage: development/tooling/coverage.md
      - Documentation: development/tooling/documentation.md
      - Packaging: development/tooling/packaging.md
      - CI/CD: development/tooling/ci.md
    - Security: development/security.md
    - Repository: "https://gitlab.com/xfbs/passgen"
    - Coverage: "https://passgen.it/coverage/lcov/"
    - Documentation: "https://passgen.it/docs/"
  - Licenses: licenses.md
  - About: about.md

extra_css:
  - stylesheets/extra.css
