site_name: Passgen

copyright: 'Copyright &copy; 2021 Patrick M. Elsen'

repo_name: 'xfbs/passgen'
repo_url: 'https://gitlab.com/xfbs/passgen'

theme: 'material'

markdown_extensions:
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Grammar: grammar.md
  - Releases: releases.md
  - Development: development.md
  - About: about.md
