site_name: Passgen
site_url: https://passgen.it

copyright: 'Copyright &copy; 2023 Patrick M. Elsen'

repo_name: 'xfbs/passgen'
repo_url: 'https://gitlab.com/xfbs/passgen'

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - kroki:
      DownloadImages: true
      DownloadDir: images

nav:
  - Home: index.md
  - Usage:
    - Usage: usage.md
    - Presets: presets.md
    - Syntax: syntax.md
    - Entropy: entropy.md
    - Randomness: randomness.md
  - Releases:
    - Releases: releases.md
    - Installation: install.md
  - Development:
    - Development: development.md
    - Building: building.md
    - Tooling: tooling.md
    - Testing: testing.md
    - Benchmarks: benchmarks.md
    - CI/CD: ci.md
    - Security: security.md
  - Licenses: licenses.md
  - About: about.md

extra_css:
  - stylesheets/extra.css
